### ISSUE TITLE
rework ToDo and fix 

### ISSUE THREAD

**Issue by simonostendorf** [FHA-FB5/discordbot#99]
Nur grob ein paar Fehler und todos, die ich gefunden habe:

- [x] #109
- [ ]  Nutzer müssen ihren Studiengang und Module wieder entfernen können
- [x]  dev-init: findOneAndUpdate sendet Error-Message obwohl es keinen Error gibt
-  [x] Semesterauswahl in selectMenu/chooseSemester/studyProgram.ts: MongoDB sort funktioniert nicht, selber Fehler dann in commands/admin/semesterAdmin.ts
- [x] Fehler in commands/admin/semesterAdmin: Cast Error für ObjectID bei module-remove
- [x] Game löschen in selectMenu/other/gameRemove: Fehler: "The dollar ($) prefixed field '$pull' in 'guilds.0.$pull' is not valid for storage"

Rücksprache:
- [ ] Cooldown entfernen für Admins
- [x] Fehler in commands/admin/semesterAdmin: Informationen in user-info sind undefinded

**Comment by simonostendorf** [comment]
> Fehler in commands/admin/semesterAdmin: Informationen in user-info sind undefinded

Damit ist das File /src/interactions/commands/admin/semesterAdmin.ts gemeint, dort werden alle Studiengänge, Module und das Semester des Nutzers ausgegeben. Diese sind in meinen Tests aber undefined. 
![image](https://user-images.githubusercontent.com/70595012/133883828-017a1639-437c-421e-b97b-e56a432ec85e.png)



> Nutzer müssen ihren Studiengang und Module wieder entfernen können

Es kann der Command des Admins ein wenig umgebaut werden, möchtest du das auch machen?



> Cooldown entfernen für Admins

Aufgrund von unnötigem Mehraufwand erstmal lassen.
